/*---------------------------------------------------------------------------
 * Please note:
 *   This file is generated by scons. All changes will be lost!
 --------------------------------------------------------------------------*/


#ifndef __VERSION_H__
#define __VERSION_H__


#define VERSION_MAJOR ${PROJECT_VERSION_MAJOR}
#define VERSION_MINOR ${PROJECT_VERSION_MINOR}
#define VERSION_MICRO ${PROJECT_VERSION_MICRO}
#define VERSION_VCS "${PROJECT_VERSION_VCS}"
#define VERSION_ALL "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_MICRO}.${PROJECT_VERSION_VCS}"


#endif  /* __VERSION_H__ */

